[book]
authors = ["Gianluca Mazza"]
language = "en"
multilingual = false
src = "src"
title = "CookieSwap docs"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]